name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_TOK }}
      - name: npm install, build
        run: |
          cd custom-generator-codelab
          npm run build --if-present
      - name: Commit and push submodule changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull
          git add --all
          git commit -m "Update submodule"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOK }}

