name: Build and Push to B2J_dist 

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOK }}
      - name: npm install, build
        run: |
          cd custom-generator-codelab
          npm run build --if-present
          cd dist
          echo $(git rev-parse HEAD) > latest_commit.txt
          ls -l
      - name: Commit files
        run: |
          ls -l
          git clone https://ValentinHerrmann:${{ secrets.GH_TOK }}@github.com/ValentinHerrmann/B2J_dist.git B2J_dist
          git remote set-url --push origin https://ValentinHerrmann:${{ secrets.GH_TOK }}@github.com/ValentinHerrmann/B2J_dist.git
          cp -r custom-generator-codelab/dist/* B2J_dist
          cd B2J_dist
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
              if [[ `git status --porcelain` ]]; then
                git add *
                git commit -m $(git rev-parse HEAD)
                git push
              else
                echo "No changes to commit"
              fi

