name: Create Release on Tag Pushed

on:
  push:
    tags:
      - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4
        -   name: Build project
            run: |
                cd custom-generator-codelab
                npm ci
                npm run build
                cd dist
                tar -czf Blockly2Java.tar.gz *
        -   name: Release
            uses: softprops/action-gh-release@v2
            with:
                body_path: CHANGELOG.MD
                files: |
                    custom-generator-codelab/dist/Blockly2Java.tar.gz
                token: ${{ secrets.GH_TOK }}

