name: Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build project
        run: |
          cd custom-generator-codelab
          npm ci
          npm run build
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOK }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOK }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./custom-generator-codelab/dist/*
            asset_name: $(basename ${{ github.ref }})
            asset_content_type: application/octet-stream